name: '\U0001F680 Feature Request'
description: Suggest an idea or enhancement
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Have an idea to improve the project? Please fill out this form!
  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "A concise description of your idea."
      placeholder: "e.g. Add support for IPv6 peers"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivation"
      description: "Why do you want this feature? What problem does it solve?"
      placeholder: "Describe the use case or problem."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "🛠️ Proposed Solution"
      description: "How would you like to see this implemented?"
      placeholder: "Describe your ideal solution."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "🔀 Alternatives Considered"
      description: "Have you considered any alternative solutions?"
      placeholder: "List any alternatives you have considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "📄 Additional Context"
      description: "Add any other context, screenshots, or references."
      placeholder: "Add context here."
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have searched existing issues."
          required: true
